apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: pods
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pods
  template:
    metadata:
      labels:
        app: pods
    spec:
      containers:
        - name: container
          image: ezemas10/serverbackend3:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MONGO_URL
              value: mongodb+srv://cursobackend:cursobackend@cluster0.fpstjym.mongodb.net/
            - name: DB_NAME
              value: proyectobackend3
          imagePullPolicy: Always